export const GOALS = [
  {
    id: "homework", label: "Études", emoji: "📚",
    color: "from-blue-500 to-indigo-600", light: "bg-blue-50", accent: "text-blue-600", ring: "ring-blue-200",
    tasks: ["Faire mes devoirs", "Relire mes leçons", "Préparer mon cartable"],
    tips: [
      "Commence par la matiere la plus difficile quand tu es frais(che).",
      "Fais une pause de 5 min toutes les 25 min (technique Pomodoro).",
      "Pose tes questions à l'école plutôt que de bloquer seul(e).",
      "Un espace de travail range = un esprit concentre.",
      "Relis tes notes le soir même pour mieux retenir.",
      "Transforme tes notes en fiches colorees pour mieux mémoriser.",
      "Etudie a la même heure chaque jour pour créer une habitude.",
      "Désactive les notifications pendant tes sessions de travail.",
      "Explique la leçon à voix haute : si tu peux l'expliquer, tu la connais.",
      "Utilise la méthode Cornell pour prendre des notes efficacement.",
      "Fais des révisions espacées : revois la leçon après 1 jour, 1 semaine, 1 mois.",
      "Bois de l'eau régulièrement, ton cerveau fonctionne mieux hydraté.",
      "Dors suffisamment : le sommeil consolide la memoire.",
      "Commence par les exercices faciles pour prendre de l'élan.",
      "Crée des associations mentales pour retenir les formules.",
      "Travaille en groupe de temps en temps pour echanger les points de vue.",
      "Lis l'énoncé deux fois avant de commencer un exercice.",
      "Fais un plan avant de rédiger une dissertation.",
      "Utilise des applications comme Anki pour les flashcards.",
      "Récompense-toi apres chaque session de travail réussie.",
    ],
    challenges: [
      "Fais tes devoirs sans regarder ton telephone pendant 30 min.",
      "Explique une leçon à voix haute comme si tu l'enseignais.",
      "Crée un résumé colore d'une leçon difficile.",
      "Fais un quiz sur tes leçons de la semaine.",
      "Lis 10 pages d'un livre scolaire sans interruption.",
      "Refais un ancien examen en conditions réelles.",
      "Apprends 10 nouveaux mots de vocabulaire aujourd'hui.",
      "Écris un résumé de 5 lignes sur ce que tu as appris aujourd'hui.",
      "Fais 3 exercices de maths sans calculatrice.",
      "Crée une carte mentale sur un sujet que tu trouves difficile.",
      "Révise pendant 1 heure sans regarder ton telephone.",
      "Pose une question à ton professeur demain.",
      "Organise ton classeur ou tes notes numeriques.",
      "Fais une session Pomodoro complète (25 min travail + 5 min pause).",
      "Écris les dates importantes du mois dans ton agenda.",
    ],
  },
  {
    id: "creative", label: "Projet creatif", emoji: "🎨",
    color: "from-pink-500 to-rose-600", light: "bg-pink-50", accent: "text-pink-600", ring: "ring-pink-200",
    tasks: ["Travailler sur mon projet", "Explorer une nouvelle idee", "Partager ma creation"],
    tips: [
      "L'inspiration vient en faisant, pas en attendant.",
      "Garde un carnet d'idées toujours avec toi.",
      "Regarde le travail d'autres créateurs pour t'inspirer.",
      "Même 15 minutes par jour font une grande difference.",
      "Les erreurs font partie du processus creatif.",
      "Impose-toi des contraintes : elles stimulent la creativite.",
      "Prends des photos de ce qui t'inspire dans la rue.",
      "Écoute de la musique instrumentale pour entrer dans le flow.",
      "Fais des croquis rapides sans te juger.",
      "Expose ton travail même imparfait : le feedback est precieux.",
      "Essaie un nouveau medium ou outil que tu n'as jamais utilise.",
      "Copie le style d'un artiste que tu admires pour apprendre.",
      "Crée a la même heure chaque jour pour ritualiser la pratique.",
      "Documente ton processus creatif en photos ou videos.",
      "Rejoins une communaute de createurs pour rester motivé.",
      "Fixe-toi un projet avec une deadline pour avancer.",
      "Alterne entre création et consommation d'art pour t'inspirer.",
      "Accepte que les premières versions soient imparfaites.",
      "Collabore avec un autre créateur pour voir les choses autrement.",
      "Prends du recul sur ton travail en le regardant le lendemain.",
    ],
    challenges: [
      "Crée quelque chose en utilisant seulement 3 couleurs.",
      "Fais un projet en 10 minutes chrono.",
      "Inspire-toi d'un objet du quotidien pour créer.",
      "Partage ta création avec quelqu'un aujourd'hui.",
      "Dessine ou écris pendant 20 minutes sans lever le stylo.",
      "Crée une piece en utilisant uniquement des materiaux recyclés.",
      "Fais un autoportrait ou une description de toi-même.",
      "Reproduis une oeuvre que tu admires pour apprendre sa technique.",
      "Crée quelque chose inspire par ta chanson preferee du moment.",
      "Publié une creation sur les reseaux sociaux aujourd'hui.",
      "Fais un projet collaboratif avec quelqu'un.",
      "Crée quelque chose en 5 minutes : quantite avant qualité.",
      "Explore un style artistique que tu n'as jamais essaye.",
      "Transforme une vieille creation en quelque chose de nouveau.",
      "Crée une série de 3 pieces sur le même theme.",
    ],
  },
  {
    id: "organization", label: "Organisation", emoji: "🗂️",
    color: "from-amber-500 to-orange-600", light: "bg-amber-50", accent: "text-amber-600", ring: "ring-amber-200",
    tasks: ["Planifier ma journée", "Ranger mon espace", "Cocher mes tâches"],
    tips: [
      "Écris tes 3 priorités du jour chaque matin.",
      "Un endroit pour chaque chose, chaque chose a sa place.",
      "Utilise des couleurs pour categoriser tes tâches.",
      "Prépare tes affaires du lendemain le soir.",
      "Révise ton planning chaque dimanche soir.",
      "La regle des 2 minutes : si ca prend moins de 2 min, fais-le maintenant.",
      "Découpe les grandes tâches en petites etapes actionnables.",
      "Utilise la méthode GTD pour vider ton esprit.",
      "Bloque des plages horaires dans ton agenda pour chaque tâche.",
      "Fais un bilan hebdomadaire chaque vendredi soir.",
      "Limite ta liste de tâches a 5 elements par jour.",
      "Traite tes emails en lot, pas en continu.",
      "Crée des templates pour les tâches repetitives.",
      "Utilise la matrice Eisenhower pour prioriser.",
      "Automatise ce qui peut l'être pour gagner du temps.",
      "Dis non aux tâches qui ne correspondent pas à tes priorités.",
      "Planifie du temps libre dans ton agenda.",
      "Fais une revue mensuelle de tes objectifs.",
      "Garde ton bureau (physique et numerique) propre.",
      "Commence chaque journée par la tâche la plus importante.",
    ],
    challenges: [
      "Range ton bureau en moins de 5 minutes.",
      "Planifie toute ta semaine en un seul tableau.",
      "Élimine 3 choses dont tu n'as plus besoin.",
      "Prépare ton sac/cartable la veille pendant 7 jours.",
      "Vide ta boite mail : archive ou supprime tout.",
      "Crée un système de classement pour tes documents.",
      "Fais une liste de toutes tes tâches en attente.",
      "Identifie et élimine une habitude qui te fait perdre du temps.",
      "Planifie tes repas de la semaine en avance.",
      "Nettoie et organise ton espace de travail complètement.",
      "Définis tes 3 objectifs principaux pour le mois.",
      "Crée une routine matinale et suis-la pendant 7 jours.",
      "Désabonné-toi de 10 newsletters inutiles.",
      "Organise tes photos ou fichiers numeriques.",
      "Fais une liste de courses optimisee par rayon.",
    ],
  },
  {
    id: "sport", label: "Sport & Santé", emoji: "⚡",
    color: "from-green-500 to-emerald-600", light: "bg-green-50", accent: "text-green-600", ring: "ring-green-200",
    tasks: ["Faire mon activité physique", "Boire assez d'eau", "Bien dormir"],
    tips: [
      "Commence petit : 10 minutes par jour c'est déjà super.",
      "Trouve une activité que tu aimes vraiment.",
      "L'échauffement est aussi important que l'entraînement.",
      "Le repos fait partie de la progression.",
      "Hydrate-toi avant, pendant et après l'effort.",
      "Dors 7 a 9 heures par nuit pour optimiser ta récupération.",
      "Mange des protéines après l'entraînement pour reconstruire les muscles.",
      "Varie tes entraînements pour eviter la monotonie.",
      "Écoute ton corps : la douleur est un signal d'alarme.",
      "Fixe-toi des objectifs SMART : spécifiques, mesurables, atteignables.",
      "Entraîne-toi avec un partenaire pour rester motivé.",
      "Prends des photos de progression pour voir les résultats.",
      "La régularité bat l'intensité sur le long terme.",
      "Prépare ta tenue de sport la veille pour éliminer les excuses.",
      "Marche au moins 8000 pas par jour.",
      "Evite les ecrans 1 heure avant de dormir.",
      "Mange des fruits et legumes a chaque repas.",
      "Fais des étirements chaque matin pour commencer la journée.",
      "Reduis le sucre et les aliments transformes progressivement.",
      "Célèbre chaque petite victoire sportive.",
    ],
    challenges: [
      "Fais 20 sauts à la corde ou jumping jacks maintenant.",
      "Marche ou cours 15 minutes sans t'arrêter.",
      "Essaie un nouveau sport ou exercice aujourd'hui.",
      "Fais des étirements pendant 10 minutes ce soir.",
      "Fais 50 squats repartis dans la journée.",
      "Bois 2 litres d'eau aujourd'hui.",
      "Dors avant 23h ce soir.",
      "Fais une seance de yoga ou meditation de 10 minutes.",
      "Prends les escaliers toute la journée.",
      "Fais 10 pompes maintenant.",
      "Marche 10 000 pas aujourd'hui.",
      "Mange 5 fruits et legumes aujourd'hui.",
      "Fais une planche de 1 minute.",
      "Cours pendant 20 minutes sans t arreter.",
      "Fais une seance de HIIT de 15 minutes.",
      "Evite tout ecran 1 heure avant de dormir ce soir.",
      "Prépare tes repas de demain ce soir.",
      "Fais 100 sauts en etoile repartis dans la journée.",
      "Essaie une nouvelle recette saine.",
      "Fais une balade de 30 minutes en pleine nature.",
    ],
  },
]

export const getGoalById = (id) => GOALS.find(g => g.id === id)

export function getDailyContent(goalId, dateStr) {
  const goal = getGoalById(goalId)
  if (!goal) return null
  const seed = dateStr.replace(/-/g, "").slice(-4)
  return {
    tip: goal.tips[parseInt(seed.slice(0, 2)) % goal.tips.length],
    challenge: goal.challenges[parseInt(seed.slice(2, 4)) % goal.challenges.length],
  }
}