functionsDirectory = "C:\\Users\\Adam\\.kiro\\projet\\App changement\\goal-tracker\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []

[build]
publish = "C:\\Users\\Adam\\.kiro\\projet\\App changement\\goal-tracker\\dist"
publishOrigin = "config"
commandOrigin = "ui"
functions = "C:\\Users\\Adam\\.kiro\\projet\\App changement\\goal-tracker\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]